return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "black",
      "clang-format",
      "clangd",
      "cmakelang",
      "cmakelint",
      "codelldb",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "neocmakelsp",
      "prettier",
      "python-lsp-server",
      "ruff",
      "rust-analyzer",
      "shellcheck",
      "shfmt",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "taplo",
      "tinymist",
      "typstyle",
      "tinymist",
      "tree-sitter-cli",
      "typescript-language-server",
      "uv",
      "vtsls",
      "yaml-language-server",
    },
    ui = {
      icons = {
        package_installed = "✓",
        package_pending = "➜",
        package_uninstalled = "✗",
      },
    },
  },
}
